config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'courses/index'
  # get 'courses/:id', to: 'courses#show', as: :course
  resources :courses do
    get 'lessons/preview', to: 'lessons#preview'
    resources :lessons, only: [ :index, :new, :create ]    
    resources :enrollments, only: [ :index ] do 
      collection { post :import, :preview_import }
    end
    resources :lessons_schedules, only: [ :create, :update ]
  end

  resources :lessons_schedules, only: [ :destroy ]

  resources :lessons, only: [ :show, :edit, :update, :destroy ] do
    get 'setup', to: 'lessons#setup'
  end
  resources :course_periods, only: [ :create, :update, :destroy ]

  resources :schools, only: [ :new, :create, :edit, :update] do
    resources :faculties, only: [ :index, :new, :edit, :create, :update ]
  end

  resources :faculties, only: [] do 
    resources :periods, only: [ :create, :update]
  end

  resources :periods, only: [ :destroy ]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_for :students, controllers: { 
  #   sessions: 'students/sessions',
  #   registrations: 'students/registrations' 
  # } 

  devise_for :students
  devise_for :users


  root to: 'pages#home'

  get 'pages/login', to: 'pages#login'
  get 'pages/signup', to: 'pages#signup'
  get 'pages/dashboard', to: 'pages#dashboard'
end

app/views/layouts/navigations/_sidenav.html.erb
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav sb-shadow-right sb-sidenav-light">
      <div class="sb-sidenav-menu">
          <div class="nav accordion" id="accordionSidenav">
              <div class="sb-sidenav-menu-heading">
                Home
              </div>
              <%= link_to pages_dashboard_path, class: 'nav-link' do %>
                <div class="sb-nav-link-icon">
                  <i data-feather="activity"></i>
                </div>
                  Dashboard
              <% end %>
              <% if user_signed_in? %>
                <%= render 'layouts/navigations/user_sidenav' %>
              <% elsif student_signed_in? %>
                <%= render 'layouts/navigations/student_sidenav' %>
              <% end %>
          </div>
      </div>
    </nav>
  </div>

app/views/layouts/navigations/_student_sidenav.html.erb
  <div class="sb-sidenav-menu-heading">Courses</div>
  <% current_student.courses.each do |course| %>
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts-<%= course.id %>" aria-expanded="false" aria-controls="collapseLayouts">
          <% icon = course.class_type == 'speaking' ? 'message-square' : 'pen-tool'  %>
          <div class="sb-nav-link-icon">
            <i data-feather=<%= icon %>></i>
          </div>
          <%= course.name %>
          <div class="sb-sidenav-collapse-arrow">
            <i class="fas fa-angle-down"></i>
          </div>
    </a>
    <div class="collapse" id="collapseLayouts-<%= course.id %>" data-parent="#accordionSidenav">
      <nav class="sb-sidenav-menu-nested nav accordion" id="accordionSidenavLayout">
          <%= link_to "Lessons", course_lessons_path(course), class: 'nav-link' %>
          <a class="nav-link" href="layout-static.html">Grades</a>
      </nav>
    </div>
  <% end %>

app/views/layouts/navigations/_top_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand shadow navbar-light bg-white" id="sidenavAccordion">

  <% path_to_display = member_signed_in? ? pages_dashboard_path : root_path %>
  
  <%= link_to path_to_display, class: 'navbar-brand d-none d-sm-block' do %><span style="color: darkgoldenrod;"><i class="fas fa-book" style="transform: rotate(-20deg);"></i></span><span class="logo-text ml-2">Classkeeper</span><% end %>
  
  <% if user_signed_in? || student_signed_in? %>
  <div class="d-flex justify-content-between w-100">
  <button class="btn sb-btn-icon sb-btn-transparent-dark order-1 order-lg-0 mr-lg-2" id="sidebarToggle" href="#"><i data-feather="menu"></i></button>

<ul class="navbar-nav align-items-center">
      <li class="nav-item dropdown no-caret mr-3 sb-dropdown-notifications">
          <a class="btn sb-btn-icon sb-btn-transparent-dark dropdown-toggle" id="navbarDropdownAlerts" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="bell"></i></a>
          <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownAlerts">
              <h6 class="dropdown-header sb-dropdown-notifications-header"><i class="mr-2" data-feather="bell"></i>Alerts Center</h6>
              <a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><div class="sb-dropdown-notifications-item-icon bg-warning"><i data-feather="activity"></i></div>
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-details">December 29, 2019</div>
                      <div class="sb-dropdown-notifications-item-content-text">This is an alert message. It's nothing serious, but it requires your attention.</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><div class="sb-dropdown-notifications-item-icon bg-info"><i data-feather="bar-chart"></i></div>
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-details">December 22, 2019</div>
                      <div class="sb-dropdown-notifications-item-content-text">A new monthly report is ready. Click here to view!</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><div class="sb-dropdown-notifications-item-icon bg-danger"><i class="fas fa-exclamation-triangle"></i></div>
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-details">December 8, 2019</div>
                      <div class="sb-dropdown-notifications-item-content-text">Critical system failure, systems shutting down.</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><div class="sb-dropdown-notifications-item-icon bg-success"><i data-feather="user-plus"></i></div>
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-details">December 2, 2019</div>
                      <div class="sb-dropdown-notifications-item-content-text">New user request. Woody has requested access to the organization.</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-footer" href="javascript:void(0);">View All Alerts</a>
          </div>
      </li>

      <li class="nav-item dropdown no-caret mr-3 sb-dropdown-notifications">
          <a class="btn sb-btn-icon sb-btn-transparent-dark dropdown-toggle" id="navbarDropdownMessages" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="mail"></i></a>
          <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownMessages">
              <h6 class="dropdown-header sb-dropdown-notifications-header"><i class="mr-2" data-feather="mail"></i>Message Center</h6>
              <a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><img class="sb-dropdown-notifications-item-img" src="https://source.unsplash.com/vTL_qy03D1I/60x60" />
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                      <div class="sb-dropdown-notifications-item-content-details">Emily Fowler · 58m</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-item" href="javascript:void(0);"
                  ><img class="sb-dropdown-notifications-item-img" src="https://source.unsplash.com/4ytMf8MgJlY/60x60" />
                  <div class="sb-dropdown-notifications-item-content">
                      <div class="sb-dropdown-notifications-item-content-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                      <div class="sb-dropdown-notifications-item-content-details">Diane Chambers · 2d</div>
                  </div></a
              ><a class="dropdown-item sb-dropdown-notifications-footer" href="javascript:void(0);">Read All Messages</a>
          </div>
      </li>
      <li class="nav-item dropdown no-caret mr-3 sb-dropdown-user">
          <a class="btn sb-btn-icon sb-btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_member.photo.attached? %>
            <%= cl_image_tag(current_member.photo.key, width: 40, gravity: "face", default_image: 'default_avatar.png') %></a>
          <% else %>
            <%= cl_image_tag('default_avatar.png', width: 40, :gravity=>"face") %></a>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownUserImage">
              <h6 class="dropdown-header d-flex align-items-center">
                  <div class="sb-dropdown-user-details">
                      <div class="sb-dropdown-user-details-name"><%= current_member.full_name %></div>
                      <div class="sb-dropdown-user-details-email"><%=  %></div>
                  </div>
              </h6>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="javascript:void(0);"
                  ><div class="sb-dropdown-item-icon"><i data-feather="settings"></i></div>
                  Account</a
              >
                  <%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %><div class="sb-dropdown-item-icon"><i data-feather="log-out"></i></div>
                  Logout <% end %>
          </div>
      </li>

  </ul>
    </div>
  <% else %>
<div style='position: absolute; right: 1.8rem; top: 0.8rem;'>
  <%= link_to new_student_registration_path, class: 'btn btn-outline-primary btn-sm' do %>Sign Up<% end %>
  <%= link_to new_student_session_path, class: 'ml-2 btn btn-primary btn-sm' do %>Log In<% end %>
</div>
  <% end %>
</nav>

app/views/layouts/navigations/_user_sidenav.html.erb
  <div class="sb-sidenav-menu-heading">
    Courses
      <%= link_to new_course_path do %><span class="sb-nav-link-icon sb-btn-transparent- float-right">
          <i data-feather="plus-square"></i>
      </span>
      <% end %>
  </div>
  
  <% unless current_user.schools.empty? %>
    
    <% current_user.schools.each_with_index do |school, index| %>
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts-<%= index %>" aria-expanded="false" aria-controls="collapseLayouts-<%= index %>">
        <div class="sb-nav-link-icon"><i data-feather="home"></i></div>
        <%= school.name %>
        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
      </a>
      <div class="collapse show" id="collapseLayouts-<%= index %>" data-parent="#accordionSidenav">
          <nav class="sb-sidenav-menu-nested nav accordion" id="accordionSidenavLayout">
            <% school.courses.where(user_id: current_user.id).each do |course| %>
              <%= link_to course_path(course), class: 'nav-link' do %>
              <% icon_type = course.class_type == 'Speaking' ? 'message-circle' : 'edit-2' %>
                    <div class="sb-nav-link-icon"><i data-feather=<%= icon_type %>></i></div><%= course.name %>                  
                    <% unless course.course_periods.empty? %>
                       <% course.course_periods.ordered.first(2).each do |course_period| %>
                        <% course_period_string = "#{course_period.day} #{course_period.period.period_number.to_s}" %>
                         <span class="badge badge-light d-flex align-items-center ml-2" style='border: #e1e1e0 solid 1px; color: grey; font-weight: 100; background: transparent;'>
                        <%= course_period_string %></span>
                       <% end %>
                    <% end %>
              <% end %>
            <% end %>
          </nav>
      </div>
    <% end %>

    <% else %>
    <span class='pl-4'>No courses yet... 😿</span>
    
  <% end %>
              