config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'courses/index'
  # get 'courses/:id', to: 'courses#show', as: :course
  resources :courses do
    get 'lessons/preview', to: 'lessons#preview'
    resources :lessons, only: [ :index, :new, :create ]    
    resources :enrollments, only: [ :index ] do 
      collection { post :import, :preview_import }
    end
    resources :lessons_schedules, only: [ :create, :update ]
  end

  resources :lessons_schedules, only: [ :destroy ]

  resources :lessons, only: [ :show, :edit, :update, :destroy ] do
    get 'setup', to: 'lessons#setup'
  end
  resources :course_periods, only: [ :create, :update, :destroy ]

  resources :schools, only: [ :new, :create, :edit, :update] do
    resources :faculties, only: [ :index, :new, :edit, :create, :update ]
  end

  resources :faculties, only: [] do 
    resources :periods, only: [ :create, :update]
  end

  resources :periods, only: [ :destroy ]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_for :students, controllers: { 
  #   sessions: 'students/sessions',
  #   registrations: 'students/registrations' 
  # } 

  devise_for :students
  devise_for :users


  root to: 'pages#home'

  get 'pages/login', to: 'pages#login'
  get 'pages/signup', to: 'pages#signup'
  get 'pages/dashboard', to: 'pages#dashboard'
end

app/views/shared/_authentication_layout.html.erb
<div id="layoutAuthentication_content" class='bg-primary' style='height: 100%;'>
<main>
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-5">
              <div class="card shadow-lg border-0 rounded-lg mt-5">
                  <div class="card-header justify-content-center"><h3 class="font-weight-light my-4"><%= title %></h3></div>
                  <div class="card-body">
                    <%= yield %>
                  </div>
                  <div class="card-footer text-center">
                      <%= render "shared/links" %>
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert" style='position: absolute;'>
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br /><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %> 
<%#end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br /><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br /><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br /><br />
<% end %>

<%- if resource_name == :student && controller_name == 'sessions' %>
  <%= link_to " 👨‍🏫 Log in as a Teacher ", new_user_session_path %><br />
<% end %>

<%- if resource_name == :user && controller_name == 'sessions' %>
  <%= link_to " 👩‍🎓 Log in as a Student ", new_student_session_path %><br />
<% end %>

<%- if resource_name == :student && controller_name == 'registrations' %>
  <%= link_to " 👩‍🏫 Sign up as a teacher ", new_user_registration_path %> <br />
<% end %>

<%- if resource_name == :user && controller_name == 'registrations' %>
  <%= link_to " 👩‍🎓 Sign up as a student ", new_student_registration_path %> <br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %>
  <% end %>
<% end %>

app/views/shared/_log_in_form.html.erb
<%= devise_error_messages! %>
    <% flash.each do |key, value| %>
       <div class="flash text-danger text-center <%= key %>"><%= value %></div>
    <% end %>
<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email", class: 'form-control py-4' },
                label_html: { class: 'small mb-1' },
                placeholder: 'Enter email address',
                wrapper_html: { class: 'form-group'}
    %>
    <%= f.input :password,
                required: true,
                input_html: { autocomplete: "current-password", class: 'form-control py-4' },
                label_html: { class: 'small mb-1' },
                placeholder: 'Enter password',
                wrapper_html: { class: 'form-group'} %>
    <% if devise_mapping.rememberable? %>
    <%= f.input :remember_me, as: :boolean, wrapper_html: { class: 'form-group' } %>
        <% end %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in", class: 'btn btn-primary' %>
  </div>
  


<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? || student_signed_in? %>
  <%= link_to courses_path, class: "navbar-brand" do %>
    <span class="fas fa-school mr-2"></span> classkeeper 
  <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-brand" do %>
    <span class="fas fa-school mr-2"></span> classkeeper 
  <% end %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, 
          class: "avatar dropdown-toggle", 
          id: "navbarDropdown", 
          data: { toggle: "dropdown" }, 
          'aria-haspopup': true, 
          'aria-expanded': false 
          %>
          
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% elsif student_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_student.photo.url, 
          class: "avatar dropdown-toggle", 
          id: "navbarDropdown", 
          data: { toggle: "dropdown" }, 
          'aria-haspopup': true, 
          'aria-expanded': false 
          %>
          
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_student_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
              <% else %>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Student", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_student_session_path, method: :delete, class: "dropdown-item" %>
          </div>
              <li class="nav-item">
        <%= link_to "Login", pages_login_path, class: "nav-link" %>
              
              </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_page_header.html.erb
<div class="sb-page-header pb-10 sb-page-header-dark bg-gradient-primary-to-secondary">
      <div class="container-fluid">
          <div class="sb-page-header-content py-5">
              <h1 class="sb-page-header-title" style='display: inline;'>
                    <% if local_variables.include?(:feather_icon)%><div class="sb-page-header-icon"><i data-feather=<%= feather_icon %>></i></div><% end %>
                    <%= title %>
              </h1>
              <% if local_variables.include?(:subtitle) %>
                <div class="sb-page-header-subtitle"><%= subtitle %></div>
              <% end %>
                    <%= yield %>
          </div>
      </div>
  </div>

app/views/shared/_page_header_light.html.erb
<div class="sb-page-header pb-10 sb-page-header-light bg-white shadow">
      <div class="container-fluid">
          <div class="sb-page-header-content py-5">
              <h1 class="sb-page-header-title" style='display: inline;'>
                    <% if local_variables.include?(:feather_icon)%><div class="sb-page-header-icon"><i data-feather=<%= feather_icon %>></i></div><% end %>
                    <%= title %>
              </h1>
              <% if local_variables.include?(:subtitle) %>
                <div class="sb-page-header-subtitle"><%= subtitle %></div>
              <% end %>
                    <%= yield %>
          </div>
      </div>
  </div>

app/views/shared/_passwords_new.html.erb
<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="form-group">
    <%= f.label :email, email_type %>
    <%= f.email_field :email, class: 'form-control', autofocus: true, autocomplete: "email" %>
  </div>

  <div class="actions">
    <%= f.submit "Send me reset password instructions", class: 'btn btn-outline-primary btn-sm' %>
  </div>
<% end %>

app/views/shared/_sign_up_form.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :given_name,
                      label: 'Given name / 下の名前',
                      required: true,
                      autofocus: true %>
        <%= f.input :family_name,
                     label: 'Family name / 名字',
                      required: true,
                      autofocus: true %>
        <%= f.input :photo %>
        <%# <%= f.input :photo_cache, as: :hidden %>
        <% if local_assigns[:student] %>
        <%= f.input :gender,
                      required: true,
                      autofocus: true,
                      collection: [['female', 'Female'], ['male', 'Male'], ['non-binary', 'Non-binary']], label_method: :second, value_method: :first,
                      as: :radio_buttons,
                      error: 'Please select a gender'
                      %>
          <%= f.input :student_number,
          label: 'Student number / 学籍番号',
                        required: true,
                        autofocus: true %>
        <% end %>              
        <%= f.input :email,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :password,
                    required: true,
                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                    required: true,
                    input_html: { autocomplete: "new-password" } %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Sign up", class: 'btn btn-primary' %>
      </div>
    <% end %>