config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'courses/index'
  # get 'courses/:id', to: 'courses#show', as: :course
  resources :courses do
    get 'lessons/preview', to: 'lessons#preview'
    resources :lessons, only: [ :index, :new, :create ]    
    resources :enrollments, only: [ :index ] do 
      collection { post :import, :preview_import }
    end
    resources :lessons_schedules, only: [ :create, :update ]
  end

  resources :lessons_schedules, only: [ :destroy ]

  resources :lessons, only: [ :show, :edit, :update, :destroy ] do
    get 'setup', to: 'lessons#setup'
  end
  resources :course_periods, only: [ :create, :update, :destroy ]

  resources :schools, only: [ :new, :create, :edit, :update] do
    resources :faculties, only: [ :index, :new, :edit, :create, :update ]
  end

  resources :faculties, only: [] do 
    resources :periods, only: [ :create, :update]
  end

  resources :periods, only: [ :destroy ]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_for :students, controllers: { 
  #   sessions: 'students/sessions',
  #   registrations: 'students/registrations' 
  # } 

  devise_for :students
  devise_for :users


  root to: 'pages#home'

  get 'pages/login', to: 'pages#login'
  get 'pages/signup', to: 'pages#signup'
  get 'pages/dashboard', to: 'pages#dashboard'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course_schedule
  belongs_to :course_period
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [ :show ]

  def index
    @course = Course.find(params[:course_id])
    @lessons = policy_scope(@course.lessons)
  end

  def setup
    @lesson = Lesson.find(params[:lesson_id])
    authorize @lesson
    @course = @lesson.course
  end

  def show
    authorize @lesson
    @course = @lesson.course
  end

  def new
    @course = Course.find(params[:course_id])
    @faculty = @course.faculty
    @course_period = CoursePeriod.new
    @course_periods = CoursePeriod.where(course_id: @course.id)
    @lessons_schedule = LessonsSchedule.new
    @school = @course.school
    @lesson = Lesson.new(course_id: params[:course_id])
    @period = Period.new
    authorize @lesson
  end

  def create
  end

  def destroy
  end

  private
  
  def lesson_params
    params.require(:lesson).permit(:course_id)
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end
end

app/views/lessons/_lessons_table.html.erb
<table id='dttb' className='table table-hover'>
  <thead>
    <tr>
      <th>Week</th>
      <th>Date</th>
      <th>Time</th>
      <th>Activities</th>
      <th>Homework</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% lessons.each do | lesson | %>
      <tr>
        <td><%= lesson.week %></td>
        <td><%= lesson.date_with_day(lesson.date) %></td>
        <td><%= lesson.course_period.period.class_time %></td>
        <td></td>
        <td></td>
        <td><%= link_to current_member.class == User ? "Setup" : "Enter", current_member.class == User ? lesson_setup_path(lesson) : lesson_path(lesson) %></td>
      </tr>
  <% end %>
  </tbody>
</table>