config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'courses/index'
  # get 'courses/:id', to: 'courses#show', as: :course
  resources :courses do
    get 'lessons/preview', to: 'lessons#preview'
    resources :lessons, only: [ :index, :new, :create ]    
    resources :enrollments, only: [ :index ] do 
      collection { post :import, :preview_import }
    end
    resources :lessons_schedules, only: [ :create, :update ]
  end

  resources :lessons_schedules, only: [ :destroy ]

  resources :lessons, only: [ :show, :edit, :update, :destroy ] do
    get 'setup', to: 'lessons#setup'
  end
  resources :course_periods, only: [ :create, :update, :destroy ]

  resources :schools, only: [ :new, :create, :edit, :update] do
    resources :faculties, only: [ :index, :new, :edit, :create, :update ]
  end

  resources :faculties, only: [] do 
    resources :periods, only: [ :create, :update]
  end

  resources :periods, only: [ :destroy ]

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # devise_for :students, controllers: { 
  #   sessions: 'students/sessions',
  #   registrations: 'students/registrations' 
  # } 

  devise_for :students
  devise_for :users


  root to: 'pages#home'

  get 'pages/login', to: 'pages#login'
  get 'pages/signup', to: 'pages#signup'
  get 'pages/dashboard', to: 'pages#dashboard'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update]

  def index
    @courses = Course.where(user: current_user)
  end

  def show
    authorize @course
    @enrollments = Enrollment.where(course_id: params[:id])
    @lessons = @course.lessons
  end

  def new
    @course = Course.new
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user 
    if @course.save
      # set the faculty school id because form doesn't update it
      @course.faculty.school_id = @course.school_id
      @course.faculty.save
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def edit
    authorize @course
  end

  def update
    @course = Course.find(params[:id])
    @course.update(course_params)
    if @course.save
      respond_to do |format|
        # an html request means the user is actually editing the course or adding lessons
        format.html { redirect_to course_path(@course), notice: 'Course successfully updated!' }
        # a ajax request means they are creating lessons
        format.js do
        end
      end
    else
      render 'edit'
    end
    authorize @course
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end
  
  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:school_id, :faculty_id, :name, :description, :start_date, :end_date, :class_type, :classroom, :class_number, :lessons_per_week, :weeks_per_course, faculty_attributes: [:id, :name, :max_absences, :school_id], school_attributes: [:id, :name], lessons_attributes: [:_destroy, :id, :date, :objective, :course_period_id, :holiday, :week, :lessons_schedules_id] )
  end
end

app/views/courses/_course_form.html.erb
<%= simple_form_for(course) do |f| %>
  

<% if action_name == 'new' %>
  
<div class='mb-4' data-controller='course-form'>
    <%= f.association :school, 
      collection: School.select_value,
      selected:  course&.faculty&.school&.id,
      include_blank: true,
      input_html: { class: 'remote-select', data: { target: 'course-form.courseSchool', action: 'change->course-form#getFaculties' } },
      wrapper_html: { id: 'original-course-input', data: { target: 'nested-form.school_input' } }      
    %>

    <%= f.association :faculty,
      collection: Faculty.select_values(course&.school),
      selected: course&.faculty&.id,
      input_html: { id: 'course_faculty', data: { target: 'course-form.courseFaculty' } },
      wrapper_html: { class: 'mt-3', id: 'origin-faculty-input' }      
    %>
</div>
<% end %>


  <div class="form-row">
    <%= f.input :name, label: 'Course Name', wrapper_html: { class: 'col' } %>
    <%= f.input :classroom, label: 'Classroom', wrapper_html: { class: 'col'} %>
    <%= f.input :class_number, label: 'Class Number', wrapper_html: { class: 'col' } %>
    <%= f.input :class_type, collection: ['Speaking', 'Writing'], include_blank: true, label: 'Class Focus', wrapper_html: { class: 'col' } %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/courses/_students_table.html.erb
<table id='dttb' class='table table-hover'>
  <thead>
    <tr>
      <th>Student number</th>
　　　　　　　　　<th>Name in Japanese</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
  <% enrollments.each do | enrollment | %>
    <tr>
      <td><%= enrollment.student.student_number %></td>
      <td><%= enrollment.student.full_name_kanji %></td>
      <td><%= enrollment.student.given_name %></td>
      <td><%= enrollment.student.family_name %></td>
      <td><%= enrollment.student.gender %></td>
      <td><%= enrollment.student.email %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/edit.html.erb
<main>
  <%= render layout: 'shared/page_header', locals: { title: @course.name, subtitle: 'Edit course', feather_icon: 'edit' } do %>
    <ol class="breadcrumb mt-4 mb-0">
        <li class="breadcrumb-item"><%= @course.school.name %></li>
        <li class="breadcrumb-item"><%= @course.faculty.name %></li>
        <li class="breadcrumb-item active"><%= @course.name %></li>
    </ol>
  <% end %>
  <div class="container-fluid mt-n10">
    <div class="card">
      <div class="card-body">
        <%= render partial: 'course_form', locals: { course: @course } %>
      </div>
    </div>
  </div>
</main>

app/views/courses/new.html.erb
<main>
  <%= render partial: 'shared/page_header', locals: { title: 'New Course', feather_icon: 'plus' } %>
  <div class="container-fluid mt-n10">
    <div class="card">
      <div class="card-body">
        <%= render partial: 'course_form', locals: { course: @course } %>
      </div>
    </div>
  </div>
</main>

app/views/courses/show.html.erb
 <main>
  <%= render layout: 'shared/page_header', locals: { title: @course.name, feather_icon: @course.feather_icon } do %>
        <%= link_to edit_course_path(@course), class: 'btn sb-btn-transparent-light sb-btn-icon edit-button', id: 'edit-course' do %> <i data-feather="edit"></i><% end %>
    <ol class="breadcrumb mt-4 mb-0">
        <li class="breadcrumb-item"><%= @course.school.name %></li>
        <li class="breadcrumb-item"><%= @course.faculty.name %></li>
        <li class="breadcrumb-item active"><%= @course.name %></li>
    </ol>

  <% end %>

  <div class="container-fluid mt-n10">
      <div class="card sb-card-collapsable">
          <a class="card-header" href="#enrolledStudents" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="enrolledStudents">
            <%= @course.enrollments.count %> Students
            <div class="sb-card-collapsable-arrow">
              <i class="fas fa-chevron-down"></i>
            </div>
          </a>
          <% show_students_or_not = @course.enrollments.empty? ? 'show' : '' %>
          <div class="collapse <%= show_students_or_not %>" id="enrolledStudents">
            <div class="card-body">
              <% if @course.enrollments.empty? %>
                <p>You have no students enrolled in this course 😔</p>
                <%= link_to course_enrollments_path(@course), class: 'btn btn-primary shadow-sm' do %>Enroll Some Students
              <% end %>

              <% else %>

              <%= render partial: 'courses/students_table', locals: { enrollments: @enrollments } %>

            <% end %>
          
            </div>
        </div>
      </div>
      <div class="card sb-card-collapsable mt-4">
      <a class="card-header" href="#lessonsCard" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="lessonsCard">
        <%= @lessons.count %> Lessons
        <div class="sb-card-collapsable-arrow">
          <i class="fas fa-chevron-down"></i>
        </div>
      </a>
      <div class="collapse show" id="lessonsCard">
        <div class="card-body">
        <%= render partial: 'lessons/lessons_table', locals: { lessons: @lessons } %>
        <%= link_to "Add some lessons", new_course_lesson_path(@course), class: 'btn btn-outline-primary' %>
          
        </div>
      </div>
      </div>
</main>